Implement sharing functionality for Enterprise
getdreams/dreams-android-sdk pull request #27
Opened 2021-04-26 11:23 UTC by mmargarit

The following payload can trigger the share 

`var payload = {"text":"Text to share", "url": "https://getdreams.com"};
if (window.JSBridge) {
    window.JSBridge.share(payload);
}`

2021-04-26 16:36 UTC, ninaniiranen requested changes
Some nitpicking for the comments, but we should verify that the intent was sent.
Also the commit messages should follow https://www.conventionalcommits.org/en/v1.0.0/ so that we can auto-generate changelogs with https://github.com/conventional-changelog/standard-version#cli-usage.

2021-04-26 16:36 UTC, ninaniiranen commented on sdk/src/androidTest/java/com/getdreams/views/DreamsViewTest.kt
> +       assertTrue(latch.await(5, TimeUnit.SECONDS))
We should verify that the share intent was sent.

2021-04-26 16:36 UTC, ninaniiranen commented on sdk/src/main/java/com/getdreams/events/Event.kt
> +     * Event sent when share should be triggered in Dreams .
Rouge space before the full stop punctuation.

2021-04-26 16:36 UTC, ninaniiranen commented on sdk/src/main/java/com/getdreams/connections/webview/ResponseInterface.kt
> +     * The user requests share dialog to be prompted
Missing full stop.

2021-04-26 19:48 UTC, mmargarit commented
haha I missed klint format here :) 
Fixed linting issues here , will rneed to esearch how to verify the intent ..
Thanks for the tip about commints..,didn't know 👍

2021-04-27 16:08 UTC, mmargarit commented
@ninaniiranen Added hits check with intent filter, tried to check intent content too but weirdly sometimes it gets them properly sometimes fails with null, I assume because of timeouts. Do you think check with hits is enough ?

2021-04-28 09:27 UTC, ninaniiranen approved these changes

2021-04-28 12:34 UTC, merged